# Generated by Django 6.0.1 on 2026-01-15 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HttpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date_time', models.DateTimeField(verbose_name='Request Date and Time')),
                ('http_method', models.CharField(max_length=200)),
                ('path', models.CharField(max_length=200)),
                ('headers', models.TextField()),
                ('request_body', models.TextField()),
            ],
        ),
    ]
