# Generated by Django 6.0.1 on 2026-01-25 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0002_rename_request_date_time_httprequest_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='httprequest',
            name='content_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='httprequest',
            name='ip_addr',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='httprequest',
            name='query_params',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='httprequest',
            name='response_status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='httprequest',
            name='request_body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
