# Generated by Django 6.0.1 on 2026-02-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0004_apirequest_delete_httprequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='HttpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='Request Date and Time')),
                ('http_method', models.CharField(max_length=200)),
                ('response_status', models.IntegerField(blank=True, null=True)),
                ('content_type', models.TextField(blank=True, null=True)),
                ('ip_addr', models.GenericIPAddressField(blank=True, null=True)),
                ('headers', models.TextField()),
                ('path', models.CharField(max_length=200)),
                ('query_params', models.TextField(blank=True, null=True)),
                ('request_body', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ApiRequest',
        ),
    ]
