name: Test Project

on: push

jobs:
  job_1:
    name: Testing Project
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          -- health-cmd:"pg_isready -U postgres"
          -- health-interval=10s
          -- health-timeout=5s
          -- health-retries=5
      
    env: 
      DB_NAME: webhook_db
      DB_USER: postgres
      DB_PASSWORD: 826702
      DB_HOST: localhost
      DB_PORT: 5432

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      - name: Upgrade PIP
        run: python -m pip install --upgrade pip
      - name: Install Requirements
        run: python -m pip install -r requirements.txt
      - name: Run Tests
        run: python manage.py test
    
